name: flutter_application_1
description: "Smart BP - AI Powered Health Monitoring"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- مكتبات التنبيهات والبلوتوث ---
  flutter_local_notifications: ^17.0.0
  flutter_blue_plus: ^1.31.0

  # --- مكتبات الواجهة والأيقونات ---
  cupertino_icons: ^1.0.8

  # --- مكتبات معالجة البيانات والملفات ---
  http: ^1.1.0
  csv: ^6.0.0 
  
  # --- مكتبات الـ PDF والطباعة ---
  pdf: ^3.10.8
  printing: ^5.11.1

  # --- مكتبات الرسوم البيانية والترجمة ---
  fl_chart: ^0.66.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # تم دمجها هنا

flutter:
  uses-material-design: true

  assets:
    - assets/logoB.jpg
    - assets/logo.jpg
    - assets/translations/
    - assets/data/avg_data.csv
    - assets/fonts/Amiri.ttf

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg" # ملاحظة: غيرتها لـ logo.jpg لأنها هي الموجودة في الـ assets عندك